# Build stage
FROM node:22-alpine AS build

RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev

ARG NODE_ENV=production
ARG GIT_SHA=unknown
ENV NODE_ENV=${NODE_ENV}
ENV APP_REVISION=${GIT_SHA}
LABEL org.opencontainers.image.revision=${GIT_SHA}

WORKDIR /opt

COPY package.json package-lock.json ./
RUN npm config set fetch-retry-maxtimeout 600000 -g && npm ci

ENV PATH /opt/node_modules/.bin:$PATH

WORKDIR /opt/app

COPY . .

RUN npm run build
WORKDIR /opt
RUN npm prune --omit=dev


# Runtime stage
FROM node:22-alpine

RUN apk add --no-cache vips-dev

ARG NODE_ENV=production
ARG GIT_SHA=unknown
ENV NODE_ENV=${NODE_ENV}
ENV APP_REVISION=${GIT_SHA}
LABEL org.opencontainers.image.revision=${GIT_SHA}

WORKDIR /opt

COPY --from=build /opt/node_modules ./node_modules

WORKDIR /opt/app

COPY --from=build /opt/app ./

ENV PATH /opt/node_modules/.bin:$PATH

RUN chown -R node:node /opt/app

USER node

EXPOSE 1337

CMD ["npm", "run", "start"]
